### ISSUE TITLE
UI won't stay open

### ISSUE THREAD

**Issue by pmk1c** [cpoppema/pass-browser-firefox#1]
I'm using Firefox Dev Edition 57. When clicking on the pass-browser icon, the UI sometimes won't open and when it does, it will close itself, when trying to focus the password input field.

**Comment by cpoppema** [comment]
Hi @pmk1c, thanks for reporting!

I have installed Firefox 57.0b3 (normal and dev) and what I'm seeing is that the autofocus for the password input field doesn't work and that needs fixing, but otherwise it seems to work OK. Can you perhaps tell me what your dev edition's complete version number is (eg. including the ".0b3") ? Also, what operating system are you using ?

**Comment by pmk1c** [comment]
I'm using the flatpak version on Fedora 26. But the problem also occured when using Firefox Dev Binary.

Now I noticed the same problem with another add-on. It seems as if the popup closes when I try to focus any password field.

**Comment by pmk1c** [comment]
When debugging the add-on I get this error, whenever I click the password lock:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src moz-extension://a2565a95-f291-43e2-97c3-99447221a4c7”). Source: onfocusin attribute on DIV element.
```

**Comment by pmk1c** [comment]
When switching to Wayland session on Fedora it works (I was using X11 before). So this is definitely not a bug with your add-on, maybe not even with Firefox, but with some Fedora weirdities regarding X11.

**Comment by cpoppema** [comment]
I'm glad you figured it out and thanks for reporting back! :+1:
